import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-gray-100 h-screen grid place-items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-96 bg-white shadow-lg rounded-xl overflow-hidden">
        <div className="py-3 px-5">
          <h1 className="font-bold text-base mb-2">Contacts</h1>

          <ul className="space-y-2">
            <li className="p-3 hover:bg-gray-100 cursor-pointer transition-colors rounded-md">
              <div className="flex flex-row items-center gap-3">
                <div className="w-1.5 h-1.5 bg-green-500 rounded-xl"></div>
                <div className="flex flex-row flex-grow justify-between items-center">
                  <span className="font-medium">Tighten Co.</span>

                  <span className="text-sm text-gray-400">Member</span>
                </div>
              </div>
            </li>

            <li className="p-3 bg-gray-100 cursor-pointer transition-colors rounded-md">
              <div className="flex flex-row items-center gap-3">
                <div className="w-1.5 h-1.5 bg-green-500 rounded-xl"></div>
                <div className="flex flex-row flex-grow justify-between items-center">
                  <span className="font-medium">Taylor Otwell</span>

                  <span className="text-sm text-gray-600 font-semibold">
                    Team
                  </span>
                </div>
              </div>
            </li>

            <li className="p-3 hover:bg-gray-100 cursor-pointer transition-colors rounded-md">
              <div className="flex flex-row items-center gap-3">
                <div className="w-1.5 h-1.5 bg-green-500 rounded-xl"></div>
                <div className="flex flex-row flex-grow justify-between items-center">
                  <span className="font-medium">Adam Wathan</span>

                  <span className="text-sm text-gray-400">Member</span>
                </div>
              </div>
            </li>

            <li className="p-3 hover:bg-gray-100 cursor-pointer transition-colors rounded-md">
              <div className="flex flex-row items-center gap-3">
                <div className="w-1.5 h-1.5 bg-green-500 rounded-xl"></div>
                <div className="flex flex-row flex-grow justify-between items-center">
                  <span className="font-medium">Adam Wathan</span>

                  <span className="text-sm text-gray-400">Member</span>
                </div>
              </div>
            </li>

            <li className="p-3 hover:bg-gray-100 cursor-pointer transition-colors rounded-md">
              <div className="flex flex-row items-center gap-3">
                <div className="w-1.5 h-1.5 bg-green-500 rounded-xl"></div>
                <div className="flex flex-row flex-grow justify-between items-center">
                  <span className="font-medium">Adam Wathan</span>

                  <span className="text-sm text-gray-400">Member</span>
                </div>
              </div>
            </li>
          </ul>
        </div>

        <div className="bg-gray-100 py-3 px-5">
          <div className="flex flex-row justify-end gap-2">
            <button className="py-2 px-5 transition-all hover:bg-gray-200 active:scale-95 text-black font-medium rounded-md">
              Cancel
            </button>
            <button className="bg-teal-600 transition-all py-2 px-5 active:scale-95 text-white hover:bg-teal-700 rounded-md">
              Invite
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
